import Head from 'next/head'
import { Header, Banner, Title, News, Footer } from '@/components'
import { useState } from 'react';



export default function Home() {
  const [isMenuOpen, setIsMenuOpen] = useState(false);

  return (
    <>
      <Head>
        <title>News HomePage Main</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-full relative py-10 px-5 md:px-60 md:py-10">
        <Header isMenuOpen={isMenuOpen} setIsMenuOpen={setIsMenuOpen}/>
        <div className={`w-full flex flex-col gap-6 mt-4 ${isMenuOpen && ""} md:flex-row`}>
          <div className='w-full h-full flex flex-col gap-4'>
            <Banner/>
            <Title/>
          </div>
          <News/>
        </div>
        <Footer/>
      </main>
    </>
  )
}
